### ISSUE TITLE
Graphics driver reset hangs the application

### ISSUE THREAD

**Issue by Death111** [doubleSlashde/KeepTime#5]
If the graphics driver is reset, an exception in the loop is thrown while updating the taskbaricon
`Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Unrecognized image loader: null
	at javafx.scene.image.WritableImage.loadTkImage(WritableImage.java:240)
	at javafx.scene.image.WritableImage.access$000(WritableImage.java:46)
	at javafx.scene.image.WritableImage$1.loadTkImage(WritableImage.java:51)
	at javafx.scene.Scene.doSnapshot(Scene.java:1236)
	at javafx.scene.Node.doSnapshot(Node.java:1864)
	at javafx.scene.Node.snapshot(Node.java:1942)
	at de.doubleslash.keeptime.view.ViewController.updateTaskbarIcon(ViewController.java:785)
	at de.doubleslash.keeptime.view.ViewController.lambda$initialize$29(ViewController.java:446)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(Unknown Source)
	at de.doubleslash.keeptime.view.time.Interval.debounceAndExecuteCallbacks(Interval.java:52)
	at de.doubleslash.keeptime.view.time.Interval.lambda$createTimeLine$0(Interval.java:37)
	at com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(TimelineClipCore.java:239)
	at com.sun.scenario.animation.shared.TimelineClipCore.playTo(TimelineClipCore.java:180)
	at javafx.animation.Timeline.impl_playTo(Timeline.java:176)
	at javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)
	at com.sun.scenario.animation.shared.InfiniteClipEnvelope.timePulse(InfiniteClipEnvelope.java:110)
	at javafx.animation.Animation.impl_timePulse(Animation.java:1102)
	at javafx.animation.Animation$1.lambda$timePulse$25(Animation.java:186)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.animation.Animation$1.timePulse(Animation.java:185)
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:514)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$403(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)`

**Comment by Death111** [comment]
Can't fix this error. All JavaFX apps will hang if driver is reset and hardware acceleration is used. You can start the application with flag -Dprism.order=sw to force software rendering.
Added bat file starting the app using software renderer.
